version: 2
updates:
  - package-ecosystem: bundler
    directory: /core/kaal
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /core/kaal-activerecord
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /core/kaal-sequel
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /gems/kaal-rails
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
