#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
gemfile_path = File.expand_path('../Gemfile', __dir__)
require 'bundler/setup' if File.exist?(gemfile_path)
require 'kaal/cli'

Kaal::CLI.start(ARGV)
