# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'kaal', path: '../../core/kaal'
  gem 'kaal-sequel', path: '../../core/kaal-sequel'
  gem 'mysql2'
  gem 'pg', '~> 1.1'
  gem 'rack-test'
  gem 'redis', '~> 5.0'
  gem 'reek'
  gem 'rspec'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'sequel', '~> 5.0'
  gem 'sinatra'
  gem 'sqlite3'
end

group :test do
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end

group :development do
  gem 'ruby-lsp', require: false
  gem 'ruby-lsp-rspec', require: false
end
