# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'kaal', path: '../../core/kaal'
  gem 'kaal-activerecord', path: '../../core/kaal-activerecord'
  gem 'mysql2'
  gem 'pg', '~> 1.1'
  gem 'redis', '~> 5.0'
  gem 'reek'
  gem 'rspec'
  gem 'rspec-rails', '~> 8.0.0'
  gem 'rubocop-factory_bot'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-rspec_rails'
  gem 'sqlite3'
end

group :test do
  gem 'fakeredis'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end

group :development do
  gem 'ruby-lsp', require: false
  gem 'ruby-lsp-rspec', require: false
end
