#!/bin/sh

. "${SCRIPT_DIR}/run-common"

run_suite() {
  suite_name="$1"
  suite_dir="$2"

  cd "${REPO_ROOT}/${suite_dir}"

  if gemfiles=$(suite_gemfiles "${suite_dir}"); then
    for gemfile in ${gemfiles}; do
      run_cmd_env \
        "${suite_name}-$(gemfile_label "${gemfile}")-rubocop" \
        BUNDLE_GEMFILE="${REPO_ROOT}/${suite_dir}/${gemfile}" \
        bin/rubocop
    done
    return 0
  fi

  run_cmd "${suite_name}-rubocop" bin/rubocop
}
